api:
  dashboard: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8080"

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true

providers:
  docker:
    exposedByDefault: false
    network: traefik-proxy

certificatesResolvers:
  myresolver:
    acme:
      email: fabienfiette@hotmail.fr
      storage: acme.json
      httpChallenge:
        entryPoint: web
